apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: swe645-1
  name: swe645-1
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: swe645-1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: swe645-1
    spec:
      containers:
        - image: swe645group/swe645_hw2
          name: swe645-1
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: swe645-1
  name: swe645-1-hpa-munr
  namespace: default
spec:
  maxReplicas: 5
  metrics:
    - resource:
        name: cpu
        targetAverageUtilization: 80
      type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: swe645-1
---
apiVersion: v1
kind: Service
metadata:
  name:  swe645-srv
  labels:
    run: swe645-1
spec:
  type: NodePort
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8080
    nodePort: 31748
  selector:
    app: swe645-1
